# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Читательский клуб
email: projects@alexsukhotin.com
description: Читательский клуб
baseurl: "/readingclub" # the subpath of your site, e.g. /blog
url: "http://sagamor.github.io" # the base hostname & protocol for your site
texts-url: "http://readingclub.alexsukhotin.com/texts/"
recordings-url: "http://readingclub.alexsukhotin.com/recordings/"

# Build settings
markdown: kramdown
exclude: [vendor]
